//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketplatformm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anket()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public string anketId { get; set; }
        public string anketKodu { get; set; }
        public string anketAdi { get; set; }
        public string anketKatId { get; set; }
        public int anketSoruSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
    }
}
